<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Bluehost\\Plugin\\WP\\McpSchema\\' => array($vendorDir . '/wordpress/php-mcp-schema/src'),
    'Bluehost\\Plugin\\WP\\MCP\\' => array($vendorDir . '/wordpress/mcp-adapter/includes'),
);
