<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit1476caa865f12c2d6adef8d0e05c5a7f
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Bluehost\Plugin\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Bluehost\Plugin\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit1476caa865f12c2d6adef8d0e05c5a7f', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Bluehost\Plugin\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit1476caa865f12c2d6adef8d0e05c5a7f', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Bluehost\Plugin\Composer\Autoload\ComposerStaticInit1476caa865f12c2d6adef8d0e05c5a7f::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
