<?php
return [
	'_id'                        => '',
	'wrapper_id'                 => '',
	'parseCategories'            => ['term'],
	'heading'                    => '',
	'heading_color'              => '',
	'description'                => '',
	'desc'                       => '',
	'description_color'          => '',
	'desc_color'                 => '',
	'header_desc_text_align'     => '',
	'post_type'                  => 'event',
	'listing_tags'               => '',
	'listing_cats'               => '',
	'listing_locations'          => '',
	'maximum_posts_on_lg_screen' => 'col-lg-3',
	'maximum_posts_on_md_screen' => 'col-md-4',
	'maximum_posts_on_sm_screen' => 'col-sm-6',
	'maximum_posts_on_xs_screen' => 'col-xs-6',
	'from'                       => 'all',
	'toggle_viewmore'            => 'disable',
	'viewmore_btn_name'          => 'View more',
	'orderby'                    => 'post_date',
	'order'                      => 'DESC',
	'img_size'                   => 'medium',
	'mobile_img_size'            => '',
	'posts_per_page'             => 6,
	'custom_taxonomy_key'        => '',
	'custom_taxonomies_id'       => '',
	'extra_class'                => '',
	'css_custom'                 => ''
];
