<?php
return [
  'TYPE'                       => 'LISTINGS_TABS',
  'heading'                    => '',
  'wrapper_id'                 => '',
  'parseCategories'            => ['term'],
  'heading_color'              => '',
  'style'                      => 'grid',
  'taxonomy'                   => 'listing_cat',
  'get_term_type'              => 'term_children',
  'order'                      => 'DESC',
  'orderby_options'            => '',
  'orderby'                    => 'post_title',
  'posts_per_page'             => 6,
  'img_size'                   => 'medium',
  'number_of_term_children'    => 6,
  'radius'                     => 10,
  'listing_locations'          => '',
  'listing_location'           => '',
  'listing_cat'                => '',
  'toggle_viewmore'            => 'enable',
  'is_navigation'              => 'enable',
  'navigation_orderby'         => 'include',
  'navigation_order'           => 'DESC',
  'listing_cats'               => '',
  'terms_tab_id'               => '',
  'tab_alignment'              => 'wil-text-right',
  'maximum_posts_on_lg_screen' => 'col-lg-4',
  'maximum_posts_on_md_screen' => 'col-md-4',
  'maximum_posts_on_sm_screen' => 'col-md-12',
  'maximum_posts_on_xs_screen' => 'col-md-12',
  'post_types_filter'          => ''
];
