<?php
return [
  'TYPE'                   => 'MASONRY_TERM_BOXES',
  'parseCategories'        => ['term'],
  'group'                  => 'term',
  'isRequiredPostType'     => 'yes',
  '_id'                    => '',
  'heading'                => '',
  'heading_color'          => '',
  'desc'                   => '',
  'description'            => '',
  'description_color'      => '',
  'desc_color'             => '',
  'header_desc_text_align' => '',
  'taxonomy'               => 'listing_cat',
  'col_gap'                => 30,
  'term_redirect'          => 'search_page',
  'post_type'              => '',
  'listing_cats'           => '',
  'listing_cat'            => '',
  'listing_locations'      => '',
  'listing_location'       => '',
  'number'                 => 6,
  'image_size'             => 'large',
  'listing_tags'           => '',
  'is_hide_empty'          => 'no',
  'is_show_parent_only'    => 'no',
  'orderby'                => 'count',
  'order'                  => 'DESC',
  'extra_class'            => '',
  'css_custom'             => ''
];
