<?php
return [
  'TYPE'                       => 'GRID',
  'parseCategories'            => ['term'],
  '_id'                        => '',
  'heading'                    => 'The Latest Listings',
  'heading_color'              => '',
  'desc'                       => '',
  'desc_color'                 => '',
  'header_desc_text_align'     => '',
  'border'                     => '',
  'post_type'                  => 'listing',
  'maximum_posts_on_lg_screen' => 'col-lg-3',
  'maximum_posts_on_md_screen' => 'col-md-4',
  'maximum_posts_on_sm_screen' => 'col-sm-6',
  'maximum_posts_on_xs_screen' => 'col-xs-6',
  'orderby'                    => '',
  'order'                      => '',
  'unit'                       => 'km',
  'radius'                     => 10,
  'posts_per_page'             => 6,
  'listing_cats'               => '',
  'listing_locations'          => '',
  'listing_location'           => '',
  'taxonomy'                   => '',
  'listing_cat'                => '',
  'toggle_viewmore'            => 'disable',
  'viewmore_btn_name'          => 'View more',
  'custom_taxonomy_key'        => '',
  'custom_taxonomies_id'       => '',
  'extra_class'                => '',
  'class'                      => '',
  'css_custom'                 => ''
];
