<?php
return [
  'TYPE'                       => 'TERM_BOXES',
  'parseCategories'            => ['term'],
  'group'                      => 'term',
  'isRequiredPostType'         => 'yes',
  'heading'                    => '',
  'heading_color'              => '',
  'desc'                       => '',
  'description'                => '',
  'description_color'          => '',
  'desc_color'                 => '',
  'header_desc_text_align'     => '',
  'taxonomy'                   => 'listing_cat',
  'col_gap'                    => 30,
  'term_redirect'              => 'search_page',
  'post_type'                  => '',
  'listing_tags'                => '',
  'listing_cats'               => '',
  'listing_cat'                => '',
  'listing_locations'          => '',
  'listing_location'           => '',
  'number'                     => 6,
  'is_hide_empty'              => 'no',
  'is_show_parent_only'        => 'no',
  'image_size'                 => 'large',
  'orderby'                    => 'count',
  'maximum_posts_on_lg_screen' => 'col-lg-3',
  'maximum_posts_on_md_screen' => 'col-md-4',
  'maximum_posts_on_sm_screen' => 'col-sm-6',
  'maximum_posts_on_xs_screen' => 'col-xs-6',
  'toggle_box_gradient'        => 'enable',
  'left_gradient_color'        => '#006bf7',
  'right_gradient_color'       => '#f06292',
  'order'                      => 'DESC',
  'extra_class'                => '',
  'css_custom'                 => ''
];
